name: stomp_dart_client
homepage: https://github.com/blackhorse-one/stomp_dart
version: 0.4.4
description: Dart STOMP client for easy messaging interoperability. Build with flutter in mind, but should work for every dart application.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  web_socket_channel: ^2.0.0

dev_dependencies:
  test: ^1.23.1
  lints: ^2.0.1
  stream_channel: ^2.1.1
