name: stomp_dart
homepage: https://github.com/blackhorse-one/stomp_dart
version: 0.1.3
description: Dart STOMP client for easy messaging interoperability.
environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  meta: ^1.1.7
  web_socket_channel: ^1.1.0

dev_dependencies:
  test: ^1.9.2