name: stomp_dart_client
homepage: https://github.com/blackhorse-one/stomp_dart
version: 1.0.3
description: Dart STOMP client for easy messaging interoperability. Build with flutter in mind, but should work for every dart application.
environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  web_socket_channel: ^2.4.0

dev_dependencies:
  test: ^1.25.0
  lints: ^3.0.0
  stream_channel: ^2.1.1
